### ISSUE TITLE
Issue in building SDK

### ISSUE THREAD

**Issue by avilash** [IntelRealSense/realsense_sdk#28]
Error reads as follows - 

/sdk/src/cameras/compression/lz4_codec.cpp:67:163: error: ‘LZ4_compress_fast’ was not declared in this scope

I have lz4 installed on my computer

**Comment by zivsha** [comment]
Hi @avilash , Sorry for the super late response! 
Have you resolved this issue?

**Comment by avilash** [comment]
Yeah , Works fine on Ubuntu 16.04

**Comment by zivsha** [comment]
Great!  👍 
Do you know what was causing this (and how did you resolve)?

**Comment by avilash** [comment]
The LZ4 issue was resolved by installing LZ4 from source, but then I ran into other issues which I do not exactly remember.
I finally decided to upgrade to Ubuntu 16.04 and install from the repository itself

**Comment by zivsha** [comment]
Thanks for sharing :)
