### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by codr1** [IntelRealSense/realsense_sdk#20]
Hello.  Trying to compile on Ubuntu 16.04 I seem to be getting an interesting error

vess@vorpal:~/code/3d/experiments/realsense_sdk/build$ make
[  1%] Building CXX object sdk/src/utilities/logger/log_utils/CMakeFiles/realsense_log_utils.dir/log_utils.cpp.o
[  2%] Linking CXX shared library librealsense_log_utils.so
[  2%] Built target realsense_log_utils
[  3%] Building CXX object sdk/src/core/image/CMakeFiles/realsense_image.dir/image_base.cpp.o
[  5%] Building CXX object sdk/src/core/image/CMakeFiles/realsense_image.dir/custom_image.cpp.o
[  6%] Building CXX object sdk/src/core/image/CMakeFiles/realsense_image.dir/image_conversion_util.cpp.o
/home/vess/code/3d/experiments/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp: In static member function ‘static rs::core::status rs::core::image_conversion_util::convert(const rs::core::image_info&, const uint8_t*, const rs::core::image_info&, uint8_t*)’:
/home/vess/code/3d/experiments/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp:45:29: error: ‘applyColorMap’ is not a member of ‘cv’
                             cv::applyColorMap(color_map, dst_mat, cv::COLORMAP_HOT);
                             ^
/home/vess/code/3d/experiments/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp:45:67: error: ‘COLORMAP_HOT’ is not a member of ‘cv’
                             cv::applyColorMap(color_map, dst_mat, cv::COLORMAP_HOT);
                                                                   ^
/home/vess/code/3d/experiments/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp:48:25: error: ‘applyColorMap’ is not a member of ‘cv’
                         cv::applyColorMap(color_map, src_mat, cv::COLORMAP_HOT);
                         ^
/home/vess/code/3d/experiments/realsense_sdk/sdk/src/core/image/image_conversion_util.cpp:48:63: error: ‘COLORMAP_HOT’ is not a member of ‘cv’
                         cv::applyColorMap(color_map, src_mat, cv::COLORMAP_HOT);
                                                               ^
sdk/src/core/image/CMakeFiles/realsense_image.dir/build.make:110: recipe for target 'sdk/src/core/image/CMakeFiles/realsense_image.dir/image_conversion_util.cpp.o' failed
make[2]: *** [sdk/src/core/image/CMakeFiles/realsense_image.dir/image_conversion_util.cpp.o] Error 1
CMakeFiles/Makefile2:408: recipe for target 'sdk/src/core/image/CMakeFiles/realsense_image.dir/all' failed
make[1]: *** [sdk/src/core/image/CMakeFiles/realsense_image.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas?

**Comment by zivsha** [comment]
Hi,

The SDK requires opencv version 3.1 inparticular and other dependencies in general. The list of requirements can be viewed in the main README file.

Are you using the correct opencv?
